bootstrap/djngo/templateAndJinja/django_template_project/django_template_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("template_app/",include("template_app.urls")),
]

bootstrap/djngo/templateAndJinja/django_template_project/template_app/urls.py
from django.urls import path
from . import views

#app_name register, url kısmına yazmak için. {% url 'app_name:index'%}
app_name = "template_app"

urlpatterns = [
    path("", views.index, name="index"), #boş bırakıldığında index'e gitsin.

    path("weather/", views.weather_view, name="weatherview"), #weather'e gidilince views.weather'e gidilsin.
] 

bootstrap/djngo/templateAndJinja/django_template_project/template_app/models.py
from django.db import models

# Create your models here.

bootstrap/djngo/templateAndJinja/django_template_project/template_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse

def index(request):
    return render(request, "template_app/first.html")

    #return render(request, "template_app/first.html") #render'in index.html'i açması gerekiyor. urls.py'a geldiğinde path'de boş bırakıldığında frist.html'i render'la diyoruz.

def weather_view(request):
    weather_dictioanry= {"Paris":"30", "Rome": "20", "Madrid":[5,8,20,25], "Bordeaux": {"morning":10, "evening":20},
    "user_premium": True,
    "test": "test test Test test"} #kullanıcı user_premium

    return render(request, "template_app/weather.html", context=weather_dictioanry) #context'teki veriyi kullanmak istersekk html dosyası içinde yazdığımız yazının yanına iki süslü parantez içinden burada belirttiğimiz key isimlerini gireriz.

bootstrap/djngo/templateAndJinja/django_template_project/template_app/templates/template_app/first.html
{% extends 'base.html' %} <!--basehtmlden kalıtım alacağız(inheritance)-->
{% load static %} <!--static yükleyeceğiz deriz.-->

{% block content %} <!--testhtmlde nereye yazdıysak bunu burası orada görünecektir-->
<h1>Friends</h1>
<img src="{% static 'template_app/friends.jpeg' %}" alt="friends">
{% endblock %}

bootstrap/djngo/templateAndJinja/django_template_project/template_app/templates/template_app/weather.html
{% extends 'base.html' %} <!--basehtmlden kalıtım alacağız(inheritance)--> 

{% block content %} <!--testhtmlde nereye yazdıysak bunu burası orada görünecektir-->


   <h1>Weather rapor</h1>
   <br>
     
    <!--jinja syntax iki süslü parantez iç içe gösterilir--> 

   <h2>Paris:{{Paris}} </h2>  <!--Burada süslü parantez içindekiler ekranda görünmez onun yerine views'te context olarak verdiğimizden çekilen dict'teki bilgi gözükür yani jinja bile burayı bir anahtar gibi yaptık. Paris:30 olarak gzöükür ekran çıktısı.-->

   <br>
   <h2>Rome:{{Rome}}</h2>

   <br>
   <!--<h2>Bordeaux: Morning:{{Bordeaux.morning}}, Evening:{{Bordeaux.evening}}</h2> nokta morning dersek morning'teki hava derecesini getirir.-->

   <ul>
   {% for key,value in Bordeaux.items %}
     <h2><li>{{key}} : {{value}}</li></h2>
   {% endfor %}
   </ul>
  
   <br>

   <br>
   <!--<h2>Madrid:{{Madrid.0}}</h2> nokta 0 yaparsak ilk hava derecesini getiirir. Madrid:10 yazar.-->
  
  <br>
   {% if user_premium %} <!--Eğer kullanıcı premium ise Madrid'i görsün-->
    <ul>
      {% for item in Madrid  %} <!--Madrid içindeki elemanları aldık-->
        {% if item < 10 %} <!--eğer madrid 10 dereceden küçük ise -->
        <h2><li>Madrid: {{item}}, Too Cold. </li><h2> <!--Madrid içinde değerleri ekrana gösteririz.-->
          {% else %} <!--değilse normal dereceyi yazmaya devam et-->
        {% endif %}
      {% endfor %}
    </ul>
   {% endif %}

   <br>
   <h2>{{test | upper}}</h2> <!--tüm yazıyı buyuk harfle gösterir-->
   
   <br>
   <!--<h2><a href="{% url 'template_app:index' %}">Go to Index</a></h2> index'e gitme link'i veriyoruz-->

{% endblock %}

bootstrap/djngo/templateAndJinja/django_template_project/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <title>My main web app</title>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
  
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
  
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
  
        .bd-mode-toggle {
          z-index: 1500;
        }
  
        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }

        body {
          min-height: 75rem;
          padding-top: 4rem;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Weather App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'template_app:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'template_app:weatherview' %}">Weather Report</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>

  {% block content %} <!--content blok ismidir. Inheritance verilecek first htmle-->

  {% endblock %}   

<h1>END OF</h1>
</body>
</html>